config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # READ
  get 'tasks', to: 'tasks#index'
  # CREATE
  get 'tasks/new', to: 'tasks#new', as: :new
  # READ
  get 'tasks/:id', to: 'tasks#show', as: :task
  # CREATE
  post 'tasks', to: 'tasks#create'
  # UPDATE
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  # DELETE
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy

  # CHECK TASK
  patch 'tasks/:id/check', to: 'tasks#check', as: :check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy check]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def check
    @task.completed = !@task.completed
    @task.save
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<div class="container d-flex justify-content-around">
  <% @tasks.each do |task| %>
    <%= link_to check_path(task), method: :patch do  %>
      <% if task.completed %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
    <% end %>

    <p><%= link_to task.title, task_path(task) %></p>
    <%= link_to task_path(task), method: :delete, data: {:confirm => "Are you sure?" } do  %>
      <i class="far fa-trash-alt"></i>
    <% end %>
    <br>
  <% end %>
</div>
<p class="ml-10"><%= link_to '+ Create Task', new_path %></p>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= link_to 'Edit task', edit_path %></p>
<p><%= link_to 'Back to list', tasks_path %></p>